version: '3.8'

services:
  db:
    image: nhutpro/ayasan-postgres:latest
    container_name: ayasan_postgres
    environment:
      POSTGRES_USER: ayasan_user
      POSTGRES_PASSWORD: ayasan_password
      POSTGRES_DB: ayasan_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: